// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPN9E1bUpK2AjQK-ksZ0UXNvKB3hB5jqA',
    appId: '1:124416372203:android:be79f2e5d71d27c7f97dae',
    messagingSenderId: '124416372203',
    projectId: 'zorixo-9e45f',
    storageBucket: 'zorixo-9e45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOSKZd491NzMQ8NwTjSp2NJ23pA6B1bE',
    appId: '1:124416372203:ios:ccfe23cbeae523b2f97dae',
    messagingSenderId: '124416372203',
    projectId: 'zorixo-9e45f',
    storageBucket: 'zorixo-9e45f.firebasestorage.app',
    androidClientId: '124416372203-n7aqjns69sjvc1e17tqc139u7ckogv8i.apps.googleusercontent.com',
    iosClientId: '124416372203-a4hg2g9puem28eio5h8pt94n7r0qmb9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

}